security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: us_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false            
        verify:
            pattern: ^/v1/api/verify
            stateless: true
            anonymous: true
        refresh:
            pattern: ^/v1/api/auth/refresh
            stateless: true
            anonymous: true
        login:
            pattern:  ^/v1/api/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /v1/api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                password_path: password
        register:
            pattern: ^/v1/api/auth/register
            stateless: true
            anonymous: true
        api:
            pattern:   ^/v1/api
            stateless: true
            guard:
                authenticators: 
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            anonymous: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/v1/api/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/v1/api/verify, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/v1/api/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/v1/api/auth/resetpaswd, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/v1/api/auth/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1/api, roles: ROLE_USER }